apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: downwardapi-injector-webhook-deployment
  namespace: kube-system
  labels:
    app: downwardapi-injector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: downwardapi-injector
    spec:
      containers:
        - name: downwardapi-injector
          image: pmoncadaisla/downwardapi-injector:1.0
          imagePullPolicy: Always
          args:
            - -downwardapiCfgFile=/etc/webhook/config/downwardapiconfig.yaml
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      volumes:
        - name: webhook-certs
          secret:
            secretName: downwardapi-injector-webhook-certs
        - name: webhook-config
          configMap:
            name: downwardapi-injector-webhook-configmap
