apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: downwardapi-injector-webhook-cfg
  labels:
    app: downwardapi-injector
webhooks:
  - name: downwardapi-injector.morven.me
    clientConfig:
      service:
        name: downwardapi-injector-webhook-svc
        namespace: kube-system
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchExpressions:
        - key: downwardapi-injector-disabled
          operator: DoesNotExist
