apiVersion: v1
kind: Service
metadata:
  name: downwardapi-injector-webhook-svc
  namespace: kube-system
  labels:
    app: downwardapi-injector
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: downwardapi-injector
